Repository spryker/robotframework-suite-tests, pull requests merged in 2023-11, with the labels that each got.

#644 CC-31028 Updated demoshop API tests after integration.
  tests/api/b2b/glue/customer_endpoints/addresses/negative.robot
  tests/api/b2b/glue/customer_endpoints/customers/negative.robot
  tests/api/b2b/glue/order_endpoints/orders/positive.robot
  tests/api/b2c/glue/customer_endpoints/addresses/negative.robot
  tests/api/mp_b2b/glue/customer_endpoints/addresses/negative.robot
  tests/api/mp_b2b/glue/customer_endpoints/customers/negative.robot
  tests/api/mp_b2b/glue/orders_endpoints/positive.robot
  tests/api/mp_b2c/glue/customer_endpoints/addresses/negative.robot
Labels: enhancement, request-review

#676 CC-31659: Added missing content type header to Service Type tests
  tests/api/suite/bapi/service_points/service_types/negative.robot
Labels: bug

#697 CC-25880 Changed product with upselling products
  resources/environments/environments_api_suite.json
  tests/api/suite/glue/general_product_endpoints/upselling_products/positive.robot
Labels: bug

#695 CC-31859: Restrict access to BAPI endpoints for merchant users
  resources/environments/environments_api_suite.json
  tests/api/suite/bapi/push_notification_endpoints/push_notification_provides/positive.robot
  tests/api/suite/bapi/push_notification_endpoints/push_notification_subscriptions/negative.robot
  tests/api/suite/bapi/push_notification_endpoints/push_notification_subscriptions/positive.robot
  tests/api/suite/bapi/warehouse_user_assignments/negative.robot
  tests/api/suite/bapi/warehouse_user_assignments/positive.robot
Labels: bug, request-review

#704 CC-31859: Restrict access to BAPI endpoints for merchant users for b2c-mp.
  resources/environments/environments_api_mp_b2c.json
  tests/api/mp_b2c/bapi/push_notification_endpoints/push_notification_providers/positive.robot
  tests/api/mp_b2c/bapi/push_notification_endpoints/push_notification_subscriptions/negative.robot
  tests/api/mp_b2c/bapi/push_notification_endpoints/push_notification_subscriptions/positive.robot
Labels: bug

#694 CC-31600: Fixed warehouse user assignment validation
  tests/api/b2c/bapi/warehouse_user_assignments/negative.robot
  tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
  tests/api/mp_b2c/bapi/warehouse_user_assignments/negative.robot
  tests/api/mp_b2c/bapi/warehouse_user_assignments/positive.robot
  tests/api/suite/bapi/warehouse_user_assignments/negative.robot
  tests/api/suite/bapi/warehouse_user_assignments/positive.robot
Labels: bug, ready-for-release

#705 CC-31600: Fixed warehouse user assignment validation
  tests/api/mp_b2c/bapi/warehouse_user_assignments/positive.robot
Labels: bug

#706 CC-31859: Restrict access to BAPI endpoints for merchant users
  tests/api/mp_b2c/bapi/warehouse_user_assignments/negative.robot
Labels: bug

#698 CC-25735 Added images to product
  tests/api/suite/glue/concrete_products_endpoints/concrete_product_image_sets/positive.robot
Labels: bug

#707 CC-29261 Updated product configuration API validation.
  tests/api/suite/glue/guest_carts/guest_cart_items/negative.robot
  tests/api/suite/glue/shopping_list_endpoints/shopping_list_items/negative.robot
  tests/api/suite/glue/wishlist_endpoints/wishlist_items/negative.robot
Labels: bug

#714 CC-25472 Fixed CMS page API tests.
  resources/steps/cms_steps.robot
  tests/api/suite/glue/content_endpoints/cms_pages/positive.robot
Labels: bug, request-review

#708 CC-31839 Updated product configuration and CMS API tests.
  resources/steps/cms_steps.robot
  tests/api/b2b/glue/cart_endpoints/items/negative.robot
  tests/api/b2b/glue/content_endpoints/cms_pages/positive.robot
  tests/api/b2b/glue/shopping_list_endpoints/shopping_list_items/negative.robot
  tests/api/b2c/glue/cart_endpoints/guest_cart_items/negative.robot
  tests/api/b2c/glue/cart_endpoints/items/negative.robot
  tests/api/b2c/glue/content_endpoints/cms_pages/positive.robot
  tests/api/b2c/glue/wishlist_endpoints/wishlist_items/negative.robot
  tests/api/mp_b2b/glue/cart_endpoints/items/negative.robot
  tests/api/mp_b2b/glue/content_endpoints/cms_pages/positive.robot
  tests/api/mp_b2b/glue/shopping_list_endpoints/shopping_list_items/negative.robot
  tests/api/mp_b2c/glue/cart_endpoints/items/negative.robot
  tests/api/mp_b2c/glue/content_endpoints/cms_pages/positive.robot
  tests/api/mp_b2c/glue/guest_carts/guest_cart_items/negative.robot
  tests/api/mp_b2c/glue/wishlist_endpoints/wishlist_items/negative.robot
  tests/api/suite/glue/cart_endpoints/cart_items/negative.robot
Labels: bug, request-review
